#ifndef __PICTURE_H
#define __PICTURE_H


#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

#ifndef USE_EXTERNAL_FLASH_STORAGE
#define USE_EXTERNAL_FLASH_STORAGE	1
#endif

#define BMCALCULATOR_48PX_ADDRESS		0x90000000
#define BMCALENDAR_48PX_ADDRESS			0x90002400
#define BMCAMERA_48PX_ADDRESS			0x90004800
#define BMCHART_48PX_ADDRESS			0x90006C00
#define BMCHIP_48PX_ADDRESS				0x90009000
#define BMCLOCK_48PX_ADDRESS			0x9000B400
#define BMCONTACTS_48PX_ADDRESS			0x9000D800
#define BMDICCIONARY_48PX_ADDRESS		0x9000FC00
#define BMFACETIME_48PX_ADDRESS			0x90012000
#define BMGAME_48PX_ADDRESS				0x90014400
#define BMHOME_48PX_ADDRESS				0x90016800
#define BMMAPS_48PX_ADDRESS				0x90018C00
#define BMMUSIC_48PX_ADDRESS			0x9001B000
#define BMNOTES_48PX_ADDRESS			0x9001D400
#define BMPHOTOS_48PX_ADDRESS			0x9001F800
#define BMREMINDERS_48PX_ADDRESS		0x90021C00
#define BMSETTINGS_48PX_ADDRESS			0x90024000
#define BMSTOCKS_48PX_ADDRESS			0x90026400
#define BMVIDEO_48PX_ADDRESS			0x90028800
#define BMWEATHER_48PX_ADDRESS			0x9002AC00
#define BMWECHAT_48PX_ADDRESS			0x9002D000
#define BMBACKGROUND3_ADDRESS			0x9002F400


extern GUI_CONST_STORAGE GUI_BITMAP bmbackground;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery_full2_24px;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery_full_24px;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery_low2_24px;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery_low3_24px;
extern GUI_CONST_STORAGE GUI_BITMAP bmsd_insert2_16px;
extern GUI_CONST_STORAGE GUI_BITMAP bmsd_insert_16px;
extern GUI_CONST_STORAGE GUI_BITMAP bmsd_insert3_16px;
extern GUI_CONST_STORAGE GUI_BITMAP bmsd_removed_16px;
extern GUI_CONST_STORAGE GUI_BITMAP bmsd_removed3_16px;
extern GUI_CONST_STORAGE GUI_BITMAP bmAlarm_16x16;
extern GUI_CONST_STORAGE GUI_BITMAP bmBatteryEmpty_27x14;
extern GUI_CONST_STORAGE GUI_BITMAP * apbmCharge[];

extern GUI_CONST_STORAGE GUI_BITMAP bmCalculator_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmCalendar_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmCamera_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmChart_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmChip_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmClock_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmContacts_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmDiccionary_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmFacetime_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmGame_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmHome_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmMaps_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmMusic_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmNotes_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmPhotos_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmReminders_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmSettings_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmStocks_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmVideo_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmWeather_48px;
extern GUI_CONST_STORAGE GUI_BITMAP bmWechat_48px;


extern GUI_CONST_STORAGE GUI_BITMAP bmbackground3;

// extern GUI_CONST_STORAGE GUI_BITMAP bmCalculator_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmCalendar_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmCamera_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmChart_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmChip_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmClock_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmContacts_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmDiccionary_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmFacetime_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmGame_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmMaps_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmMusic_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmNotes_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmReminders_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmSettings_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmStocks_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmVideo_64px;
// extern GUI_CONST_STORAGE GUI_BITMAP bmWeather_64px;

#endif